### ISSUE TITLE
[Bug] Dislike still working properly. Like not working anymore.

### ISSUE THREAD

**Issue by Beefsmeller** [avi12/youtube-like-dislike-shortcut#33]
### Describe the bug

I am on OperaGX and the extension has recently stopped working. It has worked in the past, so I believe something as changing with Youtube itself to cause the issue.

### How to reproduce

Download the extension on OperaGX and try to like a video

### Expected behavior

the video should be liked after pressing the button

### What browser(s) can you reproduce the issue on?

Opera

### What OS does it occur on?

Windows

### What's the extension version you're running?

2.2.0

### Make sure the bug wasn't reported before

- [X] I'm the first one to [report](https://github.com/avi12/youtube-auto-hd/issues?q=is%3Aissue) it

**Comment by avi12** [comment]
I released update [2.2.1](../releases/tag/2.2.1), let me know if it fixes it

**Comment by avi12** [comment]
I'll close this issue for now
If it didn't fix it, feel free to reopen

**Comment by Beefsmeller** [comment]
> I'll close this issue for now If it didn't fix it, feel free to reopen

I'm not sure I can reopen it myself, but as of 2.2.1, it is still not working.

**Comment by avi12** [comment]
Try to sideload the zip

**Comment by Beefsmeller** [comment]
> Try to sideload the zip

I'm unfamiliar with how to do that

**Comment by avi12** [comment]
Try to install the extension from the Chrome Web Store directly
Opera/Opera GX doesn't particularly care if the ext comes from CWS or the Opera store

**Comment by Beefsmeller** [comment]
> Try to install the extension from the Chrome Web Store directly Opera/Opera GX doesn't particularly care if the ext comes from CWS or the Opera store

I uninstalled and reinstalled from Chrome store and it's working now. Thank you for the help.
